import { copyFile, mkdir } from 'node:fs/promises'
import { builtinModules } from 'node:module'
import process from 'process'

import esbuild from 'esbuild'

const banner = `/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin:
https://github.com/wilfriedago/obsidian-tinymist
*/
`

const prod = process.argv[2] === 'production'
const outDir = 'dist'
const sourceDir = 'src'

/**
 * `dist/` is the complete plugin folder, not just the bundle: Obsidian loads a
 * plugin from a directory containing `main.js`, `manifest.json` and
 * `styles.css` side by side. esbuild writes the first two; copying the manifest
 * in alongside them means `dist/` can be symlinked straight into a vault's
 * plugins folder, and the release workflow has one directory to upload from.
 */
const copyManifest = {
	name: 'copy-manifest',
	setup(build) {
		build.onEnd(async (result) => {
			if (result.errors.length > 0) {
				return
			}

			await mkdir(outDir, { recursive: true })

			await copyFile('manifest.json', `${outDir}/manifest.json`)
		})
	}
}

const context = await esbuild.context({
	banner: { js: banner },
	// The stylesheet is an entry point rather than a copied file, so it is
	// minified with the bundle and `pnpm dev` rebuilds it when it changes.
	entryPoints: [
		{ in: `${sourceDir}/main.ts`, out: 'main' },
		{ in: `${sourceDir}/styles.css`, out: 'styles' }
	],
	bundle: true,
	// Obsidian supplies these at runtime. Bundling our own copy of the
	// CodeMirror packages would create a second, incompatible CM6 instance.
	external: [
		'obsidian',
		'electron',
		'@codemirror/autocomplete',
		'@codemirror/collab',
		'@codemirror/commands',
		'@codemirror/language',
		'@codemirror/lint',
		'@codemirror/search',
		'@codemirror/state',
		'@codemirror/view',
		'@lezer/common',
		'@lezer/highlight',
		'@lezer/lr',
		...builtinModules
	],
	format: 'cjs',
	target: 'es2022',
	platform: 'node',
	logLevel: 'info',
	sourcemap: prod ? false : 'inline',
	treeShaking: true,
	outdir: outDir,
	minify: prod,
	plugins: [copyManifest],
	define: {
		'process.env.NODE_ENV': JSON.stringify(prod ? 'production' : 'development')
	}
})

if (prod) {
	await context.rebuild()
	await context.dispose()
	process.exit(0)
} else {
	await context.watch()
}
